Bookify.Web/Controllers/AuthorsController.cs
namespace Bookify.Web.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;
        public AuthorsController(ApplicationDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var Authors = _context.Authors.AsNoTracking().ToList();

            var viewModel = _mapper.Map<IEnumerable<AuthorViewModel>>(Authors);

            return View(viewModel);
        }

        [HttpGet]
        [AjaxOnly]



        public IActionResult Create()
        {
            return PartialView("_Form");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AuthorFormViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var author = _mapper.Map<Author>(model);
            _context.Add(author);
            _context.SaveChanges();

            var viewModel = _mapper.Map<AuthorViewModel>(author);

            return PartialView("_AuthorRow", viewModel);
        }

        [HttpGet]
        [AjaxOnly]
        public IActionResult Edit(int id)
        {
            var author = _context.Authors.Find(id);

            if (author is null)
                return NotFound();

            var viewModel = _mapper.Map<AuthorFormViewModel>(author);

            return PartialView("_Form", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(AuthorFormViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var author = _context.Authors.Find(model.Id);

            if (author is null)
                return NotFound();

            author = _mapper.Map(model, author);
            author.LastUpdate = DateTime.Now;

            _context.SaveChanges();

            var viewModel = _mapper.Map<AuthorViewModel>(author);

            return PartialView("_AuthorRow", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ToggleStatus(int id)
        {
            var author = _context.Authors.Find(id);

            if (author is null)
                return NotFound();

            author.IsDeleted = !author.IsDeleted;
            author.LastUpdate = DateTime.Now;

            _context.SaveChanges();

            return Ok(author.LastUpdate.ToString());
        }

        public IActionResult AllowItem(AuthorFormViewModel model)
        {
            var author = _context.Authors.SingleOrDefault(c => c.Name == model.Name);
            var isAllowed = author is null || author.Id.Equals(model.Id);

            return Json(isAllowed);
        }
    }
}

Bookify.Web/Controllers/BooksController.cs
using Bookify.Web.Core.Models;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using System.Linq;
using System.Linq.Dynamic.Core;

namespace Bookify.Web.Controllers
{
    public class BooksController : Controller
    {
        private readonly IWebHostEnvironment _wepHostEnvironMent;
        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        private List<string> _allowedExtensions = new() { ".jpg",".jpeg",".png" };
        private int _allowedMaxSize = 2097152;
        public BooksController(ApplicationDbContext context, IMapper mapper
            , IWebHostEnvironment wepHostEnvironMent)
        {
            _context = context;
            _mapper = mapper;
            _wepHostEnvironMent = wepHostEnvironMent;

        }

        public IActionResult Index()  
        {
            return View();
        }

        [HttpPost]
        public IActionResult GetBooks()
        {

            var skip = int.Parse(Request.Form["start"]);
            var pageSize = int.Parse(Request.Form["length"]);
            var searchValue = Request.Form["search[value]"];

            var sortColumnIndex = Request.Form["order[0][column]"];
            var sortColumn = Request.Form[$"columns[{sortColumnIndex}][name]"];
            var sortColumnDirection = Request.Form["order[0][dir]"];

            IQueryable<Book> books = _context.Books
                .Include(b => b.Author)
                 .Include(b => b.Categories)
                .ThenInclude(c => c.Category);

            if (!string.IsNullOrEmpty(searchValue))
            {
                books = books.Where(b => b.Title.Contains(searchValue) || b.Author.Name.Contains(searchValue));
            }

            books = books.OrderBy($"{sortColumn} {sortColumnDirection}");
            
            var data = books.Skip(skip).Take(pageSize).ToList();

            var mappedData = _mapper.Map<IEnumerable<BookViewModel>>(data);
                var recordsTotal = books.Count();


            var jsonData = new { recordsFiltered = recordsTotal, recordsTotal, data = mappedData };

            return Ok(jsonData);
        }
        public IActionResult Details(int id) 
        { 
            var book = _context.Books  
                .Include(b => b.Author)
                .Include(b => b.Categories)
                .ThenInclude(c => c.Category)
                .SingleOrDefault(b => b.Id == id);
            if (book is null)
                return NotFound();
            var viewModel = _mapper.Map<BookViewModel>(book);
            return View(viewModel);
        }
        public IActionResult Create()
        {
            return View("Form", PopulateViewModel());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BookFormViewModel model)
        {
             if(!ModelState.IsValid)
            {
                return View("Form", PopulateViewModel(model));
            }

            var book = _mapper.Map<Book>(model);
            if (model.Image is not null)
            {
                var extension = Path.GetExtension(model.Image.FileName);
                if (!_allowedExtensions.Contains(extension))
                {
                    ModelState.AddModelError(nameof(model.Image), Errors.NotAllowedExtensions);
                    return View("Form", PopulateViewModel(model));
                }

                if (_allowedMaxSize < model.Image.Length)
                {
                    ModelState.AddModelError(nameof(model.Image), Errors.MaxSize);
                    return View("Form", PopulateViewModel(model));
                }

                var ImageName = $"{Guid.NewGuid()}{extension}";

                var path = Path.Combine($"{_wepHostEnvironMent.WebRootPath}/Images/books", ImageName);
                var thumbPath = Path.Combine($"{_wepHostEnvironMent.WebRootPath}/Images/books/Thumb", ImageName);

                using var streem = System.IO.File.Create(path);
                await model.Image.CopyToAsync(streem);

                streem.Dispose();

                book.ImageUrl = $"/Images/books/{ImageName}";
                book.ImageThumbnailUrl = $"/Images/books/Thumb/{ImageName}";

                using var image = Image.Load(model.Image.OpenReadStream());
                var ratio = (float)image.Width / 200;
                var height =  image.Height / ratio;
                image.Mutate(i => i.Resize(width:200 ,height: (int)height));
                image.Save(thumbPath);


                
            }
            foreach (var category in model.SelectedCategories)
            {   
                book.Categories.Add(new BookCategory { CategoryId = category });
            }

            _context.Add(book);
            _context.SaveChanges();

            return RedirectToAction(nameof(Details),new {id = book.Id});
        }
        public IActionResult Edit(int id)
        {
            var book = _context.Books.Include(b => b.Categories).SingleOrDefault(b => b.Id == id);
            if (book is null)
            {
                return NotFound();
            }
            var model = _mapper.Map<BookFormViewModel>(book);
            var viewModel = PopulateViewModel(model);
            viewModel.SelectedCategories = book.Categories.Select(c => c.CategoryId).ToList();

            return View("Form", viewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BookFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Form", PopulateViewModel(model));
            }

            var book = _context.Books.Include(b => b.Categories).SingleOrDefault(b => b.Id == model.Id);
            if (book is null)
            {
                return NotFound();
            }

            if (model.Image is not null)
            {
                if (!string.IsNullOrEmpty(book.ImageUrl))
                {
                    var oldImagePath = $"{_wepHostEnvironMent.WebRootPath}{book.ImageUrl}";
                    var oldThumbPath = $"{_wepHostEnvironMent.WebRootPath}{book.ImageThumbnailUrl}";
                   
                    if (System.IO.File.Exists(oldImagePath))
                        System.IO.File.Delete(oldImagePath);

                    if (System.IO.File.Exists(oldThumbPath))
                        System.IO.File.Delete(oldThumbPath);
                }
                 
                var extension = Path.GetExtension(model.Image.FileName);
                if (!_allowedExtensions.Contains(extension))
                {
                    ModelState.AddModelError(nameof(model.Image), Errors.NotAllowedExtensions);
                    return View("Form", PopulateViewModel(model));
                }

                if (_allowedMaxSize < model.Image.Length)
                {
                    ModelState.AddModelError(nameof(model.Image), Errors.MaxSize);
                    return View("Form", PopulateViewModel(model));
                }

                var ImageName = $"{Guid.NewGuid()}{extension}";

                var path = Path.Combine($"{_wepHostEnvironMent.WebRootPath}/Images/books", ImageName);
                var thumbPath = Path.Combine($"{_wepHostEnvironMent.WebRootPath}/Images/books/Thumb", ImageName);

                using var streem = System.IO.File.Create(path);
                await model.Image.CopyToAsync(streem);

                streem.Dispose();

                model.ImageUrl = $"/Images/books/{ImageName}";
                model.ImageThumbnailUrl = $"/Images/books/Thumb/{ImageName}";

                using var image = Image.Load(model.Image.OpenReadStream());
                var ratio = (float)image.Width / 200;
                var height = image.Height / ratio;

                image.Mutate(i => i.Resize(width: 200, height: (int)height));
                image.Save(thumbPath);


            }

            else if (!string.IsNullOrEmpty(book.ImageUrl))
            {
                model.ImageUrl = book.ImageUrl;
                model.ImageThumbnailUrl = book.ImageThumbnailUrl;
            }

            book = _mapper.Map(model, book); 
            book.LastUpdate = DateTime.Now;

            foreach (var category in model.SelectedCategories)
            {
                book.Categories.Add(new BookCategory { CategoryId = category });
            }

            _context.SaveChanges();

            return RedirectToAction(nameof(Details),new {id = book.Id});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ToggleStatus(int id)
        {
            var book = _context.Books.Find(id);

            if (book is null)
                return NotFound();

            book.IsDeleted = !book.IsDeleted;
            book.LastUpdate = DateTime.Now;

            _context.SaveChanges();

            return Ok(book.LastUpdate.ToString());
        }
        public IActionResult AllowItem(BookFormViewModel model)
        {
            var book = _context.Books.SingleOrDefault(b => b.Title == model.Title && b.AuthorId == model.AuthorId);
            var isAllowed = book is null || book.Id.Equals(model.Id);

            return Json(isAllowed);
        }

        private BookFormViewModel PopulateViewModel(BookFormViewModel? Model = null)
        {
            BookFormViewModel viewModel = Model is null ? new BookFormViewModel() :  Model;

            var authors = _context.Authors.Where(a => !a.IsDeleted).ToList();
            var categories = _context.Categories.Where(a => !a.IsDeleted).ToList();

            viewModel.Authors = _mapper.Map<IEnumerable<SelectListItem>>(authors);
            viewModel.Categories = _mapper.Map<IEnumerable<SelectListItem>>(categories);
        

Bookify.Web/Controllers/CategoriesController.cs
namespace Bookify.Web.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public CategoriesController(ApplicationDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var categories = _context.Categories.AsNoTracking().ToList();

            var viewModel = _mapper.Map<IEnumerable<CategoryViewModel>>(categories);

            return View(viewModel);
        }

        [HttpGet]
        [AjaxOnly]



        public IActionResult Create()
        {
            return PartialView("_Form");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CategoryFormViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var category = _mapper.Map<Category>(model);
            _context.Add(category);
            _context.SaveChanges();

            var viewModel = _mapper.Map<CategoryViewModel>(category);

            return PartialView("_CategoryRow", viewModel);
        }

        [HttpGet]
        [AjaxOnly]
        public IActionResult Edit(int id)
        {
            var category = _context.Categories.Find(id);

            if (category is null)
                return NotFound();

            var viewModel = _mapper.Map<CategoryFormViewModel>(category);

            return PartialView("_Form", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CategoryFormViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var category = _context.Categories.Find(model.Id);

            if (category is null)
                return NotFound();

            category = _mapper.Map(model, category);
            category.LastUpdate = DateTime.Now;

            _context.SaveChanges();

            var viewModel = _mapper.Map<CategoryViewModel>(category);

            return PartialView("_CategoryRow", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ToggleStatus(int id)
        {
            var category = _context.Categories.Find(id);

            if (category is null)
                return NotFound();

            category.IsDeleted = !category.IsDeleted;
            category.LastUpdate = DateTime.Now;

            _context.SaveChanges();

            return Ok(category.LastUpdate.ToString());
        }

        public IActionResult AllowItem(CategoryFormViewModel model)
        {
            var category = _context.Categories.SingleOrDefault(c => c.Name == model.Name);
            var isAllowed = category is null || category.Id.Equals(model.Id);

            return Json(isAllowed);
        }
    }
}

Bookify.Web/Views/Shared/_Aside.cshtml
                <!--begin::Aside-->
<div id="kt_aside" class="aside card" data-kt-drawer="true" data-kt-drawer-name="aside" data-kt-drawer-activate="{default: true, lg: false}" data-kt-drawer-overlay="true" data-kt-drawer-width="{default:'200px', '300px': '250px'}" data-kt-drawer-direction="start" data-kt-drawer-toggle="#kt_aside_toggle">
    <!--begin::Aside menu-->
    <div class="aside-menu flex-column-fluid px-4">
        <!--begin::Aside Menu-->
        <div class="hover-scroll-overlay-y my-5 pe-4 me-n4" id="kt_aside_menu_wrapper" data-kt-scroll="true" data-kt-scroll-activate="true" data-kt-scroll-height="auto" data-kt-scroll-dependencies="{default: '#kt_aside_footer', lg: '#kt_header, #kt_aside_footer'}" data-kt-scroll-wrappers="#kt_aside, #kt_aside_menu" data-kt-scroll-offset="{default: '5px', lg: '75px'}">
            <!--begin::Menu-->
            <div class="menu menu-column menu-rounded menu-sub-indention fw-semibold fs-6" id="#kt_aside_menu" data-kt-menu="true">
                <!--begin:Menu item-->
                <div class="menu-item">
                    <!--begin:Menu link-->
                    <a class="menu-link" asp-controller="Home" asp-action="Index" active-when="Home">
                        <span class="menu-icon">
                            <!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
                            <span class="svg-icon svg-icon-2 ">
                                <svg width="800px" height="800px" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd" clip-rule="evenodd" d="M8 0L0 6V8H1V15H4V10H7V15H15V8H16V6L14 4.5V1H11V2.25L8 0ZM9 10H12V13H9V10Z" fill="currentColor" />
                                </svg>
                            </span>
                            <!--end::Svg Icon-->
                        </span>
                        <span class="menu-title">Home</span>
                    </a>
                    <!--end:Menu link-->
                    <!--begin:Menu link-->
                    <a class="menu-link" asp-controller="Categories" asp-action="Index" active-when="Categories">
                        <span class="menu-icon">
                            <!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
                            <span class="svg-icon svg-icon-2 ">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path d="M21 7H3C2.4 7 2 6.6 2 6V4C2 3.4 2.4 3 3 3H21C21.6 3 22 3.4 22 4V6C22 6.6 21.6 7 21 7Z" fill="currentColor" />
                                    <path opacity="0.3" d="M21 14H3C2.4 14 2 13.6 2 13V11C2 10.4 2.4 10 3 10H21C21.6 10 22 10.4 22 11V13C22 13.6 21.6 14 21 14ZM22 20V18C22 17.4 21.6 17 21 17H3C2.4 17 2 17.4 2 18V20C2 20.6 2.4 21 3 21H21C21.6 21 22 20.6 22 20Z" fill="currentColor" />
                                </svg>
                            </span>
                            <!--end::Svg Icon-->
                        </span>
                        <span class="menu-title">Categories</span>
                    </a>
                    <!--end:Menu link-->
                    <!--begin:Menu link-->
                    <a class="menu-link " asp-controller="Authors" asp-action="Index" active-when="Authors">
                        <span class="menu-icon">
                            <!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
                            <span class="svg-icon svg-icon-2 ">
                                <svg xmlns="http://www.w3.org/2000/svg" shape-rendering="geometricPrecision" text-rendering="geometricPrecision" image-rendering="optimizeQuality" fill-rule="evenodd" clip-rule="evenodd" viewBox="0 0 513.07 515.83"><path d="M65.79 0h301.26c36.19 0 65.79 29.63 65.79 65.79v384.26c0 36.15-29.63 65.78-65.79 65.78H65.79C29.63 515.83 0 486.23 0 450.05V65.79C0 29.6 29.6 0 65.79 0zm386.16 337.23h46.62c1.76 0 3.42.29 5.06.87 2.13.75 3.86 1.84 5.29 3.27l-.01.01c1.48 1.46 2.58 3.23 3.28 5.25h-.01l.01.04c.58 1.67.88 3.38.88 5.06v67.94c0 1.18-.16 2.36-.48 3.56-.08.32-.17.65-.28.99-.66 1.97-1.72 3.68-3.14 5.11a13.582 13.582 0 01-3.5 2.55c-1.84.93-3.75 1.39-5.72 1.39h-48v-96.04zm0-254.67h46.63c2.17 0 4.2.47 6.15 1.38 2.21 1.04 3.93 2.47 5.29 4.29l-.03.02c1.05 1.41 1.84 2.88 2.35 4.49l-.05.01c.52 1.61.78 3.19.78 4.79v68.04c0 1.47-.27 2.94-.82 4.37-.2.58-.46 1.15-.76 1.71-.82 1.5-1.96 2.87-3.42 4-.75.61-1.55 1.12-2.39 1.55l-.01-.01-.04.01c-1.85.93-3.74 1.4-5.67 1.4h-48.01V82.56zm0 126.07l46.62.01c2.2 0 4.24.46 6.2 1.38l-.01.02c2.19 1.03 3.9 2.45 5.26 4.26l-.03.02c.92 1.24 1.63 2.51 2.12 3.82.64 1.7.96 3.39.96 5.07v68.44c0 1.97-.46 3.87-1.4 5.72a13.33 13.33 0 01-2.51 3.49l-.02-.02c-1.1 1.09-2.27 1.95-3.51 2.57l-.03-.04c-1.85.93-3.73 1.39-5.65 1.39h-48v-96.13zm-291.62 43.29c-4.91-7.72-14.06-18.32-14.06-27.5.22-6.08 4.16-11.41 9.91-13.41-.45-7.72-.76-15.59-.76-23.38 0-4.6 0-9.24.26-13.8.24-2.89.76-5.75 1.55-8.55a49.153 49.153 0 0121.95-27.88 64.81 64.81 0 0111.91-5.7c7.6-2.73 3.84-15.43 12.11-15.6 19.32-.5 51.08 17.18 63.47 30.6a49.034 49.034 0 0112.66 31.78l-.79 33.84c3.71.77 6.78 3.38 8.13 6.93 2.64 10.7-8.44 23.97-13.59 32.48-4.76 7.84-22.92 33.19-22.92 33.36 2.57 38.29 90.7 8.29 90.7 89.18H91.98c0-79.02 92.03-53.54 91.08-89.25 0-.5-20.87-30.02-22.73-33v-.1z" fill="currentColor" /></svg>
                            </span>
                            <!--end::Svg Icon-->
                        </span>
                        <span class="menu-title">Authors</span>
                    </a>
                    <!--end:Menu link-->
                    <!--begin:Menu link-->
                    <a class="menu-link " asp-controller="Books" asp-action="Index" active-when="Books">
                        <span class="menu-icon">
                            <!--begin::Svg Icon | path: icons/duotune/general/gen002.svg-->
                            <span class="svg-icon svg-icon-2 ">
                                <svg xmlns="http://www.w3.org/2000/svg" id="Layer_1" data-name="Layer 1" viewBox="0 0 105.34 122.88">
                                    <defs>
                                        <style>.cls-1 { fill-rule: evenodd; }</style>
                                    </defs>
                                    <title>book-literature</title>
                                    <path class="cls-1" d="M17.52,0H102V94.24c-.15,2.64-3.55,2.7-7.23,2.53H16.27a9.24,9.24,0,0,0,0,18.48H98.11v-9.83h7.23v12.49a4.15,4.15,0,0,1-4.14,4.14H16.63C7.48,125.44,0,118,0,108.81V17.52A17.57,17.57,0,0,1,17.52,0ZM16.25,107.92H91.41a1.38,1.38,0,0,1,1.38,1.38v.84a1.39,1.39,0,0,1-1.38,1.38H16.25a1.39,1.39,0,0,1-1.39-1.38v-.84a1.39,1.39,0,0,1,1.39-1.38Zm0-7.14H91.41a1.38,1.38,0,0,1,1.38,1.38V103a1.39,1.39,0,0,1-1.38,1.38H16.25A1.39,1.39,0,0,1,14.86,103v-.84a1.39,1.39,0,0,1,1.39-1.38Z" fill="currentColor" />
                                </svg>
                            </span>
                            <!--end::Svg Icon-->
                        </span>
                        <span class="menu-title">Books</span>
                    </a>
                    <!--end:Menu link-->
                </div>
                <!--end:Menu item-->
            </div>
            <!--end::Menu-->
        </div>
    </div>
    <!--end::Aside menu-->
</div>
<!--end::Aside-->

Bookify.Web/Views/Shared/_DataTableCardHeader.cshtml
<div class="card-header align-items-center py-5 gap-2 gap-md-5">
    <div class="card-title">
        <div class="d-flex align-items-center position-relative my-1">
            <span class="svg-icon svg-icon-1 position-absolute ms-4">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <rect opacity="0.5" x="17.0365" y="15.1223" width="8.15546" height="2" rx="1" transform="rotate(45 17.0365 15.1223)" fill="currentColor"></rect>
                    <path d="M11 19C6.55556 19 3 15.4444 3 11C3 6.55556 6.55556 3 11 3C15.4444 3 19 6.55556 19 11C19 15.4444 15.4444 19 11 19ZM11 5C7.53333 5 5 7.53333 5 11C5 14.4667 7.53333 17 11 17C14.4667 17 17 14.4667 17 11C17 7.53333 14.4667 5 11 5Z" fill="currentColor"></path>
                </svg>
            </span>
            <input type="text" data-kt-filter="search" class="form-control form-control-solid w-250px ps-14" placeholder="Search..." />
        </div>
        <div id="kt_datatable_example_1_export" class="d-none"></div>
    </div>
    <div class="card-toolbar flex-row-fluid justify-content-end gap-5">
        <button type="button" class="btn btn-light-primary" data-kt-menu-trigger="click" data-kt-menu-placement="bottom-end">
            <span class="svg-icon svg-icon-2">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <rect opacity="0.3" width="12" height="2" rx="1" transform="matrix(0 -1 -1 0 12.75 19.75)" fill="currentColor"></rect>
                    <path d="M12.0573 17.8813L13.5203 16.1256C13.9121 15.6554 14.6232 15.6232 15.056 16.056C15.4457 16.4457 15.4641 17.0716 15.0979 17.4836L12.4974 20.4092C12.0996 20.8567 11.4004 20.8567 11.0026 20.4092L8.40206 17.4836C8.0359 17.0716 8.0543 16.4457 8.44401 16.056C8.87683 15.6232 9.58785 15.6554 9.9797 16.1256L11.4427 17.8813C11.6026 18.0732 11.8974 18.0732 12.0573 17.8813Z" fill="currentColor"></path>
                    <path opacity="0.3" d="M18.75 15.75H17.75C17.1977 15.75 16.75 15.3023 16.75 14.75C16.75 14.1977 17.1977 13.75 17.75 13.75C18.3023 13.75 18.75 13.3023 18.75 12.75V5.75C18.75 5.19771 18.3023 4.75 17.75 4.75L5.75 4.75C5.19772 4.75 4.75 5.19771 4.75 5.75V12.75C4.75 13.3023 5.19771 13.75 5.75 13.75C6.30229 13.75 6.75 14.1977 6.75 14.75C6.75 15.3023 6.30229 15.75 5.75 15.75H4.75C3.64543 15.75 2.75 14.8546 2.75 13.75V4.75C2.75 3.64543 3.64543 2.75 4.75 2.75L18.75 2.75C19.8546 2.75 20.75 3.64543 20.75 4.75V13.75C20.75 14.8546 19.8546 15.75 18.75 15.75Z" fill="currentColor"></path>
                </svg>
            </span>
            Export
        </button>
        <div id="kt_datatable_example_export_menu" class="menu menu-sub menu-sub-dropdown menu-column menu-rounded menu-gray-600 menu-state-bg-light-primary fw-semibold fs-7 w-200px py-4" data-kt-menu="true">
            <div class="menu-item px-3">
                <a href="#" class="menu-link px-3" data-kt-export="copy">
                    Copy to clipboard
                </a>
            </div>
            <div class="menu-item px-3">
                <a href="#" class="menu-link px-3" data-kt-export="excel">
                    Export as Excel
                </a>
            </div>
            <div class="menu-item px-3">
                <a href="#" class="menu-link px-3" data-kt-export="csv">
                    Export as CSV
                </a>
            </div>
            <div class="menu-item px-3">
                <a href="#" class="menu-link px-3" data-kt-export="pdf">
                    Export as PDF
                </a>
            </div>
        </div>
        <div id="kt_datatable_example_buttons" class="d-none"></div>
    </div>
</div>

Bookify.Web/Views/Shared/_Modal.cshtml
<div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalLabel">
                    @* Modal Title will be rendered here *@
                </h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @* Modal Body will be rendered here *@
            </div>
        </div>
    </div>
</div>